CSID-DGU/2024-1-OSSProj-OhYeSu-05

- README.md
- main.py
> Modify Upstream OYJ

- Kiri_app/admin.py
- Kiri_app/consumers.py
- Kiri_app/models.py
- Kiri_app/routing.py
- Kiri_app/serializers.py
- Kiri_app/urls.py
- Kiri_app/views.py
- Kiri_prj/settings.py
- Kiri_prj/urls.py
Kiri_prj, Kiri_app django 백엔드 코드 추가
> backend initial commit

- Kiri_app/models.py
- Kiri_app/views.py
> 매칭 알고리즘 틀 추가

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/mytestapp/BlockListActivity.kt
- app/src/main/java/com/example/mytestapp/MainActivity.kt
- app/src/main/java/com/example/mytestapp/MyPageFragment.kt
- app/src/main/java/com/example/mytestapp/adapter/BlockRecyclerAdapter.kt
- app/src/main/res/layout/activity_block_itemrecyclerview.xml
- app/src/main/res/layout/activity_block_recyclerview.xml
- app/src/main/res/layout/fragment_mypage.xml
차단 목록 관련 레이아웃 구현
차단 목록 관련 어댑터 구현
마이페이지 차단 목록 관리 버튼에 기능 연결
> Front: 차단 목록 및 차단 목록 관리 구현

- Kiri_app/models.py
- Kiri_app/urls.py
- Kiri_app/views.py
> backend push

- Kiri_app/views.py
- app/src/main/java/com/example/mytestapp/MainActivity.kt
- app/src/main/res/layout/item_chat_history.xml
- app/src/main/res/values/colors.xml
> Front: 메인액티비티 수정

- .idea/vcs.xml
- app/src/main/java/com/example/mytestapp/adapter/ChatAdapter.kt
- app/src/main/java/com/example/mytestapp/chat/ChatActivity.kt
- app/src/main/java/com/example/mytestapp/matchmaking/MatchmakingActivity.kt
- app/src/main/java/com/example/mytestapp/service/KiriService.kt
- app/src/main/res/layout/chat_message_item_match_request.xml
채팅 중에 사용자가 매칭하기 버튼을 누르면 "해당 사용자와 매칭을 진행하시겠습니까?"라는 창이 나타남
"네" 버튼을 누르면 상대방에게 매칭 수락/거절 버튼이 있는 채팅이 보내지며, 자신에게는 "해당 사용자에게 매칭을 신청했습니다. 상대가 매칭을 수락하면 매칭이 완료됩니다."라는 메시지가 보내짐. 
이때 각 메시지는 각각의 사용자에게만 보이도록 설정
> Front : MatchMaking 기능 추가

- app/src/main/java/com/example/mytestapp/chat/BlockUserActivity.kt
- app/src/main/java/com/example/mytestapp/model/response/loginresponse.kt
- app/src/main/java/com/example/mytestapp/sign/LoginActivity.kt
- app/src/main/java/com/example/mytestapp/sign/SignupActivity.kt
sharedpreference로 로그인한 아이디 갖고 오기
xml레이아웃과 맞춰 다이얼로그 onclick 이벤트 구현
> Front: 차단 기능 수정

- app/build.gradle.kts
- app/src/main/java/com/example/mytestapp/entitiy/ApiFactory.kt
- app/src/main/java/com/example/mytestapp/model/request/signuprequest.kt
- app/src/main/java/com/example/mytestapp/service/KiriService.kt
- app/src/main/java/com/example/mytestapp/sign/SignupActivity.kt
- build.gradle.kts
> Bug Fix : 회원가입

- app/src/main/java/com/example/mytestapp/match/MatchingING.kt
매칭 조건 입력 완료 버튼 클릭 후 매칭ING 화면 연결
1.5초 뒤에 매칭프래그먼트 나옴
> Front: MatchingING 연결

- app/src/main/java/com/example/mytestapp/MyPageFragment.kt
로그아웃 버튼 누르면 로그아웃 실행 후 로그인 액티비티로 넘어감
> Front: 로그아웃 기능 구현

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/mytestapp/entitiy/ApiFactory.kt
- app/src/main/java/com/example/mytestapp/match/MatchingOption4Activity.kt
> bug fix : ING->fragment fix 중

- Kiri_app/models.py
- Kiri_app/views.py
- app/src/main/java/com/example/mytestapp/chat/BlockUserActivity.kt
- app/src/main/java/com/example/mytestapp/model/request/BlockData.kt
> back : 차단 기능 수정중

- app/src/main/java/com/example/mytestapp/MainActivity.kt
- app/src/main/java/com/example/mytestapp/MyPageFragment.kt
- app/src/main/res/layout/fragment_mypage.xml
> Front: 마이페이지 버그 픽스

- app/src/main/java/com/example/mytestapp/chat/BlockUserActivity.kt
> Fix : Block Activity

- app/src/main/java/com/example/mytestapp/viewmodel/MatchingViewModel.kt
> Fix : chat/block/report에 해당하는 targetuser 오류 수정

- Doc/3_1_OSSProj_05_OhYeSu_최종보고서.md
- Doc/3_3_OSSProj_05_OhYeSu_최종보고서부록.md
최종 구현 화면 별 기능 설명 추가
DB명세서, API 명세서, ERD 등 추가
> Doc: 최종보고서 작성

- README.md
> Update : README

- Kiri_app/consumers.py
- Kiri_app/models.py
- Kiri_app/urls.py
- Kiri_app/views.py
> back : 채팅 기능 구현중

- app/src/main/java/com/example/mytestapp/entitiy/ApiFactory.kt
- app/src/main/res/xml/network_security_config.xml
> back : 배포 완료
